site_name: My API Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - GET Request: get-request.md
  - POST Request: post-request.md
  - PUT & PATCH: put-patch.md
  - DELETE Request: delete.md
  - REST API (Full): rest-api.md

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
